FROM python:3.13-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /code

RUN mkdir src

COPY ./requirements.txt /code/requirements.txt
COPY ./pyproject.toml /code/pyproject.toml

RUN pip install --no-cache-dir -r /code/requirements.txt
RUN pip install -e .

COPY ./src/api /code/src/api