"""add cascade to linelinetoken

Revision ID: 077503e3f2da
Revises: 6d6489d2713f
Create Date: 2026-06-26 16:49:16.170266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '077503e3f2da'
down_revision: Union[str, Sequence[str], None] = '6d6489d2713f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('line_linetokens_line_id_fkey'), 'line_linetokens', type_='foreignkey')
    op.create_foreign_key(None, 'line_linetokens', 'lines', ['line_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'line_linetokens', type_='foreignkey')
    op.create_foreign_key(op.f('line_linetokens_line_id_fkey'), 'line_linetokens', 'lines', ['line_id'], ['id'])
    # ### end Alembic commands ###
