"""add line preset

Revision ID: 6d6489d2713f
Revises: cb5052dd6dbe
Create Date: 2026-06-25 21:46:52.311946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d6489d2713f'
down_revision: Union[str, Sequence[str], None] = 'cb5052dd6dbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lines', sa.Column('preset', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lines', 'preset')
    # ### end Alembic commands ###
