"""add presets table

Revision ID: 98accd944f7d
Revises: 077503e3f2da
Create Date: 2026-07-19 01:38:22.186060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98accd944f7d'
down_revision: Union[str, Sequence[str], None] = '077503e3f2da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presets',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ws_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.drop_constraint(op.f('creators_books_book_id_fkey'), 'creators_books', type_='foreignkey')
    op.create_foreign_key(None, 'creators_books', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'creators_books', type_='foreignkey')
    op.create_foreign_key(op.f('creators_books_book_id_fkey'), 'creators_books', 'books', ['book_id'], ['id'])
    op.drop_table('presets')
    # ### end Alembic commands ###
