"""Initial

Revision ID: cb5052dd6dbe
Revises: 
Create Date: 2026-06-25 18:04:31.518196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb5052dd6dbe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ankinotes',
    sa.Column('nid', sa.BigInteger(), nullable=False),
    sa.Column('deck', sa.String(), nullable=False),
    sa.Column('text_field', sa.String(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('nid')
    )
    op.create_index(op.f('ix_ankinotes_nid'), 'ankinotes', ['nid'], unique=False)
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('original_file', sa.String(), nullable=False),
    sa.Column('thumb', sa.String(), nullable=True),
    sa.Column('static_url', sa.String(), nullable=False),
    sa.Column('total_char', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('spine', sa.JSON(), nullable=False),
    sa.Column('raw_metadata', sa.JSON(), nullable=True),
    sa.Column('stylesheets', sa.JSON(), nullable=False),
    sa.Column('progress_status', sa.String(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('last_opened', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    op.create_table('bookstokens',
    sa.Column('lemma', sa.String(), nullable=False),
    sa.Column('inflection', sa.String(), nullable=False, sqlite_on_conflict_primary_key='IGNORE'),
    sa.Column('pos', sa.String(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('inflection')
    )
    op.create_index(op.f('ix_bookstokens_inflection'), 'bookstokens', ['inflection'], unique=False)
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_id'), 'collections', ['id'], unique=False)
    op.create_table('creators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_creators_id'), 'creators', ['id'], unique=False)
    op.create_table('lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lines_id'), 'lines', ['id'], unique=False)
    op.create_table('linetokens',
    sa.Column('lemma', sa.String(), nullable=False),
    sa.Column('inflection', sa.String(), nullable=False, sqlite_on_conflict_primary_key='IGNORE'),
    sa.Column('pos', sa.String(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('inflection')
    )
    op.create_index(op.f('ix_linetokens_inflection'), 'linetokens', ['inflection'], unique=False)
    op.create_index(op.f('ix_linetokens_lemma'), 'linetokens', ['lemma'], unique=False)
    op.create_table('morphemes',
    sa.Column('lemma', sa.String(), nullable=False),
    sa.Column('inflection', sa.String(), nullable=False, sqlite_on_conflict_primary_key='IGNORE'),
    sa.Column('pos', sa.String(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('inflection')
    )
    op.create_index(op.f('ix_morphemes_inflection'), 'morphemes', ['inflection'], unique=False)
    op.create_table('options',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_options_name'), 'options', ['name'], unique=False)
    op.create_table('ankinote_morpheme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.BigInteger(), nullable=False),
    sa.Column('morph_inflection', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['morph_inflection'], ['morphemes.inflection'], ),
    sa.ForeignKeyConstraint(['note_id'], ['ankinotes.nid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('preview', sa.Text(), nullable=True),
    sa.Column('section', sa.String(), nullable=False),
    sa.Column('ch_pos', sa.Integer(), nullable=True),
    sa.Column('tok_pos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookmarks_id'), 'bookmarks', ['id'], unique=False)
    op.create_table('booktokencount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('morph_inflection', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['morph_inflection'], ['bookstokens.inflection'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booktokencount_id'), 'booktokencount', ['id'], unique=False)
    op.create_table('collections_books',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.PrimaryKeyConstraint('collection_id', 'book_id')
    )
    op.create_table('creators_books',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'creator_id')
    )
    op.create_table('lastpositions',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(), nullable=False),
    sa.Column('ch_pos', sa.Integer(), nullable=True),
    sa.Column('tok_pos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_index(op.f('ix_lastpositions_book_id'), 'lastpositions', ['book_id'], unique=False)
    op.create_table('line_linetokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_ref', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('token_inflection', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], ),
    sa.ForeignKeyConstraint(['token_inflection'], ['linetokens.inflection'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('start_ch', sa.Integer(), nullable=False),
    sa.Column('start_tok', sa.Integer(), nullable=False),
    sa.Column('stylesheets', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sections_id'), 'sections', ['id'], unique=False)
    op.create_table('tocitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('section', sa.String(), nullable=False),
    sa.Column('anchor_id', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tocitems_id'), 'tocitems', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tocitems_id'), table_name='tocitems')
    op.drop_table('tocitems')
    op.drop_index(op.f('ix_sections_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_table('line_linetokens')
    op.drop_index(op.f('ix_lastpositions_book_id'), table_name='lastpositions')
    op.drop_table('lastpositions')
    op.drop_table('creators_books')
    op.drop_table('collections_books')
    op.drop_index(op.f('ix_booktokencount_id'), table_name='booktokencount')
    op.drop_table('booktokencount')
    op.drop_index(op.f('ix_bookmarks_id'), table_name='bookmarks')
    op.drop_table('bookmarks')
    op.drop_table('ankinote_morpheme')
    op.drop_index(op.f('ix_options_name'), table_name='options')
    op.drop_table('options')
    op.drop_index(op.f('ix_morphemes_inflection'), table_name='morphemes')
    op.drop_table('morphemes')
    op.drop_index(op.f('ix_linetokens_lemma'), table_name='linetokens')
    op.drop_index(op.f('ix_linetokens_inflection'), table_name='linetokens')
    op.drop_table('linetokens')
    op.drop_index(op.f('ix_lines_id'), table_name='lines')
    op.drop_table('lines')
    op.drop_index(op.f('ix_creators_id'), table_name='creators')
    op.drop_table('creators')
    op.drop_index(op.f('ix_collections_id'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_bookstokens_inflection'), table_name='bookstokens')
    op.drop_table('bookstokens')
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_ankinotes_nid'), table_name='ankinotes')
    op.drop_table('ankinotes')
    # ### end Alembic commands ###
